# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Install dependencies
      run: npm install
      
    - name: Build with Quasar
      run: quasar build
      
    - name: Copy Build Result
      run: cp -rf  dist /home/puppy0cam/DogeStock/Web/

    - name: Copy server file
      run: cp server.cjs -f /home/puppy0cam/DogeStock/Web/server.cjs
      
    - name: Copy Credentials File
      run: cp credentials.cjs -f /home/puppy0cam/DogeStock/Web/credentials.cjs
      
    - name: Restart server
      run: pm2 restart DogeStockWeb
